export type LanguageCode = 'BN' | 'EN' | 'HI' | 'UR' | 'AR';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  flag: string;
  nativeName: string;
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'BN', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'EN', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'HI', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'UR', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'AR', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' }
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  BN: {
    // Shared / Notice Banner
    welcome_notice: "আমাদের সাইটে আপনাদের স্বাগতম। নিশ্চয় এবং সৎ ভাবে কাজ করবেন, আনলিমিটেড কাজ করবেন এবং উইথড্র করবেন। ২৪ ঘন্টার মধ্যেই পেমেন্ট পাবেন ইনশাআল্লাহ।",
    notice_title: "অফিসিয়াল ঘোষণা ও নোটিশ",
    notice_guarantee_title: "🛡️ আমাদের অফিসিয়াল নিশ্চয়তা",
    notice_guarantee_desc: "নিশ্চয় এবং সৎ ভাবে কাজ করুন, ২৪ ঘন্টার মধ্যেই পেমেন্ট পাবেন ইনশাআল্লাহ। এখানে আনলিমিটেড কাজ করতে পারবেন!",
    notice_read_close: "পঠিত হয়েছে / বন্ধ করুন",
    notice_close: "বন্ধ",
    available_balance: "চলতি ব্যালেন্স",
    withdraw: "উইথড্র",
    withdraw_action: "উইথড্র করুন",
    referrals: "রেফারেল",
    referrals_earn: "বন্ধুদের রেফার করে আয় করুন!",
    copy_referral_link: "আপনার রেফারেল লিঙ্ক কপি করুন:",
    copied_msg: "কপি করা হয়েছে! ✓",
    ads_watched: "দেখেছেন",
    ads_remaining: "বাকি আছে",
    ads_total: "সর্বমোট",
    reward_per_ad: "প্রতি এড রিওয়ার্ড মূল্য: ৳০.৫০",
    show_ad: "এড দেখুন (Show Ad)",
    ads_exhausted: "আজকের জন্য লিমিট শেষ! আগামীকাল আবার আসুন।",
    ad_desc: "এড সম্পূর্ণ লোড হওয়া পর্যন্ত এবং টাইমার শেষ হওয়া পর্যন্ত অপেক্ষা করুন। ক্লেইম বাটনে ক্লিক করলেই আপনার ওয়ালেটে বোনাস যুক্ত হবে।",
    premium_ads_hub: "প্রিমিয়াম এডস হাব",
    earn_ad_title: "ভিডিও এড দেখে প্রতিবার নিশ্চিত আয় করুন",
    daily_progress: "আজকের কাজের অগ্রগতি",
    collect_reward: "৳ রিওয়ার্ড সংগ্রহ করুন",
    sec_payout_hint: "ইউজার প্যানেল সাপোর্ট: কোনো বিজ্ঞাপন ফ্রেমে আটকে গেলে বা বাফারিংজনিত সমস্যা হলে অ্যাকাউন্ট রিলোড দিন অথবা ফাস্ট ইন্টারনেট ব্যবহার করুন।",
    task_earn: "সহজ মাইক্রো টাস্ক সম্পন্ন করে বিপুল আয় করুন!",
    task_tab: "টাস্ক",
    leaders_tab: "লিডারবোর্ড",
    home_tab: "হোম",
    ads_tab: "এডস",
    menu_tab: "মেনু",
    sign_out: "সেশন সাইন আউট করুন",
    confirm_logout: "আপনি কি নিশ্চিত যে আপনার সেশনটি সাইন আউট করতে চান?",
    total_members: "মোট সক্রিয় মেম্বার্স",
    verified_badge: "ভেরিফাইড মেম্বার",
    login_title: "প্ল্যাটফর্ম অ্যাকাউন্টে প্রবেশ করুন",
    signup_title: "নিরাপদ অ্যাকাউন্ট তৈরি করুন",
    login_prompt: "আপনার পূর্বের ডেটা দিয়ে পুনরায় প্রবেশ করুন",
    signup_prompt: "সহজ মাইক্রো ট্রাস্টেড কাজ ও নিশ্চিত আজীবন ক্যাশআউট!",
    fullname_label: "আপনার নাম",
    username_label: "ইউজারনেম",
    password_label: "পাসওয়ার্ড",
    confirm_password_label: "কনফার্ম পাসওয়ার্ড",
    refercode_label: "রেফার কোড / Sponsor Code (ঐচ্ছিক)",
    agreement_consent: "আমি CashHive-এর সকল নিয়মাবলি ও ১টি ডিভাইসে ১টি একমাত্র অ্যাকাউন্ট ব্যবহারের নীতিতে সম্মত।",
    already_member: "বিদ্যমান একাউন্টে লগইন করুন",
    new_member: "নতুন অ্যাকাউন্ট তৈরি করুন",
    language_detect_msg: "🎁 রেফারেল সোর্স ডিটেক্ট করা হয়েছে",

    // Home view specific details
    quick_withdraw_sub: "আপনার উড়ান্ত লাভ সরাসরি পেমেন্ট নিন",
    quick_invite: "বন্ধুদের ইনভাইট",
    quick_invite_sub: "জন সদস্য সফল টিম জয়েন",
    daily_bonus: "ডেইলি বোনাস",
    daily_bonus_sub: "৭ দিনের প্রতিদিন নিশ্চিত ইনকাম বোনাস",
    lucky_spin: "লাকি স্পিন হুইল",
    lucky_spin_sub: "গোল চাকা ঘুরিয়ে জিতে নিন ৩-৫ টাকা",
    complete_tasks: "টাস্ক কমপ্লিট করুন",
    watch_video_ads: "ভিডিও এডস দেখুন",
    refer_link_copy_btn: "রেফার লিংক কপি করুন",
    day: "দিন",
    active: "সক্রিয়",
    claimed: "ক্লেইমড",
    claim: "ক্লেইম করুন",
    locked: "লকড",

    // Daily bonus claim modal
    daily_bonus_title: "ডেইলি বোনাস ক্লেইম লিস্ট 🎁",
    daily_bonus_desc: "টানা ৭ দিন ক্লেইম করুন এবং প্রতিদিন আকর্ষণীয় বোনাস সরাসরি ওয়ালেটে যোগ করুন!",
    daily_bonus_already_claimed: "আপনি আজকে ইতিমধ্যে আপনার দৈনিক ক্লেইম সম্পূর্ণ করেছেন! পরবর্তী ক্লেইম করতে আগামীকাল আবার চেষ্টা করুন।",
    daily_bonus_claim_btn: "দৈনিক চেক-ইন (৳ {amount}) ক্লেইম করুন",
    daily_bonus_claimed_btn: "আজকের বোনাস নেওয়া হয়েছে!",
    daily_bonus_alert_success: "🎉 অভিনন্দন! দৈনিক চেক-ইন বোনাস হিসেবে আপনার অ্যাকাউন্টে সফলভাবে যোগ করা হয়েছে!",

    // Spin
    lucky_wheel_title: "লাকি স্পিন হুইল 🎡",
    lucky_wheel_desc: "প্রতিদিন একবার গোল চাকা ঘুরিয়ে আপনার ভাগ্য পরীক্ষা করুন! ৫ টাকা পর্যন্ত ক্যাশ জেতার সুবর্ণ সুযোগ।",
    wheel_center_text_1: "লাকি",
    wheel_center_text_2: "স্পিন",
    wheel_cycle_hint: "💡 আজকের জন্য আপনার ভাগ্য পরীক্ষা করতে চাকাটি ঘুরিয়ে দিন! প্রতিদিন ১ বার ফ্রি স্পিন করতে পারবেন।",
    wheel_spin_btn: "গোল চাকা ঘোরান (Start Spin)",
    wheel_spin_disabled: "আজকের স্পিন সম্পূর্ণ হয়েছে!",
    wheel_spinning: "চাকা ঘুরছে... দয়া করে অপেক্ষা করুন",
    wheel_alert_success: "🎉 অভিনন্দন! আপনি চাকা ঘুরিয়ে সফলভাবে জিতেছেন! সরাসরি ব্যালেন্স যোগ হয়েছে।",
    wheel_alert_empty: "😢 উফ! আজকের স্পিন ফাঁকা পড়েছে। হতাশ হবেন না, আগামীকাল আবার ঘুরিয়ে নিশ্চিত পুরস্কার জিতুন!",
    wheel_slice_empty: "ফাঁকা 😢",
    wheel_slice_taka: "৳ {amount} 💰",

    // Ads View player
    hd_sponsor_casting: "HD SPONSOR CASTING",
    buffering: "বাফারিং...",
    remaining_seconds: "অবशिष्ट {seconds} সেকেন্ড",
    ready: "READY ✓",
    server_connecting: "সার্ভারের সাথে সংযোগ স্থাপন করা হচ্ছে...",
    media_loading: "Loading dynamic media stream",
    generator_loading: "উচ্চ গতির ভিডিও লিঙ্ক জেনারেট হচ্ছে...",
    view_ad_carefully: "রিওয়ার্ড ক্লেইম করার জন্য সম্পুর্ন ভিডিওটি মনোযোগ দিয়ে দেখুন!",
    ad_reward_credited: "সরাসরি ব্যালেন্সে যোগ করা হয়েছে!",
    collect_reward_btn: "৳ রিওয়ার্ড সংগ্রহ করুন (Collect Reward)",
    user_panel_support_msg: "💡 ইউজার প্যানেল সাপোর্ট: কোনো বিজ্ঞাপন ফ্রেমে আটকে গেলে বা বাফারিংজনিত সমস্যা হলে অ্যাকাউন্ট রিলোড দিন অথবা ফাস্ট ইন্টারনেট ব্যবহার করুন।",
    ad_limit_reached_alert: "❌ দুঃখিত! আপনার আজকের দৈনিক এডস দেখার লিমিট শেষ হয়েছে। দয়া করে আগামীকাল আবার চেষ্টা করুন।",

    // Leaderboard
    leaderboard_header_title: "সেরা উপার্জনকারী (Leaderboard)",
    leaderboard_header_desc: "লাইভ সর্বোচ্চ আয়কারী লিডারবোর্ড। নিয়মিত কাজ করে শীর্ষে থাকুন!",
    your_rank: "YOUR RANK",
    total_income: "TOTAL INCOME",
    rank_and_user: "RANK & USER",
    balance: "BALANCE",
    you: "YOU",
    taka_currency: "৳ Taka",
    leaderboard_footer_tip: "প্রতি সপ্তাহে সেরা ৩ জন টপ রেট টাস্কার পাবেন সরাসরি ক্যাশ জ্যাকপোর্ট বোনাস! বেশি বেশি কাজ করুন আর লিডারবোর্ডের শীর্ষে থাকুন।",

    // Withdraw & Payment announcement limits
    withdraw_banner_title: "🔥 উইথড্র সীমা ঘোষণা (Strict Limits) 🔥",
    withdraw_banner_desc: "সর্বনিম্ন উইথড্র ১০০ টাকা এবং সর্বোচ্চ উইথড্র ২৫,০০০ টাকা!",
    payment_audited_badge: "SECURE AUDITED PAYMENT",
    withdraw_method_title: "উইথড্র মেথড নির্বাচন করুন (Withdraw Gateway)",
    withdraw_method_desc: "নিচের যেকোনো অনুমোদিত পেমেন্ট গেটওয়ের মাধ্যমে পেমেন্ট নিন।",
    mobile_wallet_number_label: "মোবাইল ওয়ালেট নম্বর (১১ ডিজিট):",
    placeholder_wallet_number: "আপনার ওয়ালেট নম্বর লিখুন (01XXXXXXXXX)",
    withdraw_amount_label: "টাকার পরিমাণ (৳ ১০০ - ২৫,০০০):",
    placeholder_withdraw_amount: "টাকার পরিমাণ লিখুন",
    withdraw_submit_btn: "উইথড্র রিকোয়েস্ট পাঠান 💸",
    withdraw_submitting: "প্রক্রিয়াকরণ হচ্ছে...",
    withdraw_success_msg: "আপনার উইথড্র রিকোয়েস্ট সফলভাবে জমা হয়েছে! আমাদের অ্যাডমিন প্যানেল ৫ থেকে ৬ ঘণ্টার মধ্যে টাকা পরিশোধ করবে।",
    withdraw_empty_err: "সঠিক টাকার অঙ্ক পূরণ করুন।",
    withdraw_phone_err: "সঠিক ১১ ডিজিটের মোবাইল ব্যাংকিং নম্বর দিন (যেমন: 017XXXXXXXX)।",
    withdraw_balance_err: "আপনার একাউন্টে পর্যাপ্ত ব্যালেন্স নেই!",
    withdraw_min_err: "দুঃখিত! সর্বনিম্ন উইথড্র লিমিট ৳ ১০০.০০ টাকা।",
    withdraw_max_err: "দুঃখিত! সর্বোচ্চ উইথড্র লিমিট ৳ ২৫,০০০.০০ টাকা।"
  },
  EN: {
    welcome_notice: "Welcome to our site. Work honestly, execute unlimited tasks, and request cashouts. You will receive payments inside 24 hours guaranteed!",
    notice_title: "Official Announcement",
    notice_guarantee_title: "🛡️ Our Official Guarantee",
    notice_guarantee_desc: "Work honestly, execute unlimited tasks, and request cashouts. You will receive payments inside 24 hours inshallah!",
    notice_read_close: "Acknowledge / Close Notice",
    notice_close: "Close",
    available_balance: "Available Balance",
    withdraw: "Withdraw",
    withdraw_action: "Withdraw Cash",
    referrals: "Referrals",
    referrals_earn: "Earn massive bonuses by referring friends!",
    copy_referral_link: "Copy your invitation link:",
    copied_msg: "Link copied! ✓",
    ads_watched: "Watched",
    ads_remaining: "Remaining",
    ads_total: "Total Limit",
    reward_per_ad: "Reward Price per Ad: ৳0.50",
    show_ad: "Watch Premium Ad",
    ads_exhausted: "Limit ended for today! Please check back tomorrow.",
    ad_desc: "Wait until the video loads completely. Click the Claim button to add reward balance instantly.",
    premium_ads_hub: "Premium Ads Hub",
    earn_ad_title: "Earn guaranteed rewards by viewing sponsoring ads",
    daily_progress: "Today's Task Progress",
    collect_reward: "Collect Active Reward",
    sec_payout_hint: "User Panel: If ads freeze or buffer, refresh the page or use a fast private network connection.",
    task_earn: "Complete easy micro tasks and boost your earnings!",
    task_tab: "Task",
    leaders_tab: "Leaders",
    home_tab: "Home",
    ads_tab: "Ads",
    menu_tab: "Menu",
    sign_out: "Sign Out Session",
    confirm_logout: "Are you sure you want to sign out from this device?",
    total_members: "Total Active Members",
    verified_badge: "Verified Member",
    login_title: "Entrance Secure Login",
    signup_title: "Create Brand New Account",
    login_prompt: "Log in with your existing account parameters",
    signup_prompt: "Join CashHive premium task & guaranteed lifetime payouts!",
    fullname_label: "Full Name",
    username_label: "Username Handle",
    password_label: "Security Password",
    confirm_password_label: "Confirm Password",
    refercode_label: "Refer / Sponsor Code (Optional)",
    agreement_consent: "I comply with CashHive Terms & One-Account-Per-Device policy.",
    already_member: "Log Into Existing Account",
    new_member: "Create New Account",
    language_detect_msg: "🎁 Referral sponsor source auto detected",

    // Home view specific details
    quick_withdraw_sub: "Get your flown profits paid instantly",
    quick_invite: "Invite Friends",
    quick_invite_sub: "members successfully joined",
    daily_bonus: "Daily Bonus",
    daily_bonus_sub: "7 days guaranteed login reward bonus",
    lucky_spin: "Lucky Spin Wheel",
    lucky_spin_sub: "Spin the circular wheel to win ৳3-5",
    complete_tasks: "Complete Tasks",
    watch_video_ads: "Watch Video Ads",
    refer_link_copy_btn: "Copy Refer Link",
    day: "Day",
    active: "Active",
    claimed: "Claimed",
    claim: "Claim Now",
    locked: "Locked",

    // Daily bonus claim modal
    daily_bonus_title: "Daily Bonus Claim List 🎁",
    daily_bonus_desc: "Claim continuously for 7 days to add attractive bonuses to your wallet!",
    daily_bonus_already_claimed: "You have already completed your daily claim today! Please try again tomorrow.",
    daily_bonus_claim_btn: "Claim Daily Check-in (৳ {amount})",
    daily_bonus_claimed_btn: "Today's Login Bonus Taken!",
    daily_bonus_alert_success: "🎉 Congratulations! Daily check-in bonus has been successfully added to your account!",

    // Spin
    lucky_wheel_title: "Lucky Spin Wheel 🎡",
    lucky_wheel_desc: "Test your luck by spinning the wheel daily once! Gold opportunity to win up to ৳5 cash.",
    wheel_center_text_1: "Lucky",
    wheel_center_text_2: "Spin",
    wheel_cycle_hint: "💡 Spin the wheel today to test your luck! You can spin for free once per day.",
    wheel_spin_btn: "Spin Wheel (Start Spin)",
    wheel_spin_disabled: "Today's Spin is Completed!",
    wheel_spinning: "Wheel is spinning... please wait",
    wheel_alert_success: "🎉 Congratulations! You have successfully won from the wheel and added to your balance!",
    wheel_alert_empty: "Oof! Today's spin resulted in empty. Try again tomorrow to win guaranteed!",
    wheel_slice_empty: "Empty 😢",
    wheel_slice_taka: "৳ {amount} 💰",

    // Ads View player
    hd_sponsor_casting: "HD SPONSOR CASTING",
    buffering: "Buffering...",
    remaining_seconds: "Remaining {seconds} Seconds",
    ready: "READY ✓",
    server_connecting: "Establishing server connection...",
    media_loading: "Loading dynamic media stream",
    generator_loading: "Generating high speed video link...",
    view_ad_carefully: "Watch the full video carefully to claim your reward!",
    ad_reward_credited: "added directly to your balance!",
    collect_reward_btn: "Collect Reward",
    user_panel_support_msg: "💡 User Panel Support: If ads freeze or experiences buffer issues, please reload the page.",
    ad_limit_reached_alert: "❌ Daily watch limit ended! Please return tomorrow.",

    // Leaderboard
    leaderboard_header_title: "Leaderboard (Top Earners)",
    leaderboard_header_desc: "Live highest earners list. Carry out regular tasking to stay top!",
    your_rank: "YOUR RANK",
    total_income: "TOTAL INCOME",
    rank_and_user: "RANK & USER",
    balance: "BALANCE",
    you: "YOU",
    taka_currency: "৳ Taka",
    leaderboard_footer_tip: "The top 3 performers of the week will receive direct Cash Jackpot Bonuses! Perform more tasks.",

    // Withdraw & Payment announcement limits
    withdraw_banner_title: "🔥 Withdrawal Limits (Strict) 🔥",
    withdraw_banner_desc: "Minimum Cashout ৳100 and Maximum Cashout ৳25,000!",
    payment_audited_badge: "SECURE AUDITED PAYMENT",
    withdraw_method_title: "Select Payout Gateway",
    withdraw_method_desc: "Receive your cashout using our reliable payout networks.",
    mobile_wallet_number_label: "Mobile Wallet Number (11 digits):",
    placeholder_wallet_number: "Enter your phone number (01XXXXXXXXX)",
    withdraw_amount_label: "Cashout Amount (৳100 - 25,000):",
    placeholder_withdraw_amount: "Enter cashout amount",
    withdraw_submit_btn: "Submit Payout Request 💸",
    withdraw_submitting: "Processing payout...",
    withdraw_success_msg: "Your withdrawal request was submitted! Our admin panel will settle within 5 to 6 hours.",
    withdraw_empty_err: "Please enter a valid amount.",
    withdraw_phone_err: "Please provide a valid 11-digit mobile wallet number.",
    withdraw_balance_err: "Insufficient wallet balance!",
    withdraw_min_err: "Sorry! Minimum withdrawal limit is ৳100.00.",
    withdraw_max_err: "Sorry! Maximum withdrawal limit is ৳25,000.00."
  },
  HI: {
    welcome_notice: "हमारी साइट पर आपका स्वागत है। ईमानदारी से काम करें, असीमित कार्य करें, और तुरंत निकासी पाएं। 24 घंटे के भीतर भुगतान गारंटेड है!",
    notice_title: "आधिकारिक घोषणा",
    notice_guarantee_title: "🛡️ हमारी आधिकारिक गारंटी",
    notice_guarantee_desc: "ईमानदारी से काम करें, असीमित कार्य करें, और तुरंत निकासी पाएं। 24 घंटे के भीतर भुगतान निश्चित है!",
    notice_read_close: "स्वीकार करें / बंद करें",
    notice_close: "बंद करें",
    available_balance: "मुख्य बैलेंस",
    withdraw: "निकासी",
    withdraw_action: "पैसे निकालें",
    referrals: "रेफरल",
    referrals_earn: "मित्रों को आमंत्रित करें और निश्चित बोनस पाएं!",
    copy_referral_link: "अपनी निमंत्रण कड़ियों को कॉपी करें:",
    copied_msg: "सफलतापूर्वक कॉपी! ✓",
    ads_watched: "देखे गए",
    ads_remaining: "शेष बचे",
    ads_total: "कुल लिमिट",
    reward_per_ad: "प्रति विज्ञापन इनाम मूल्य: ৳०.५०",
    show_ad: "विज्ञापन देखें (Show Ad)",
    ads_exhausted: "आज की सीमा समाप्त हो गई है! कृपया कल पुनः प्रयास करें।",
    ad_desc: "वीडियो पूरी तरह लोड होने तक प्रतीक्षा करें। अपने वॉलेट में बोनस जोड़ने के लिए क्लेम बटन दबाएं।",
    premium_ads_hub: "प्रीमियम विज्ञापन हब",
    earn_ad_title: "वीडियो एड देखकर हर बार निश्चित कमाई करें",
    daily_progress: "आज के कार्य की प्रगति",
    collect_reward: "इनाम प्राप्त करें",
    sec_payout_hint: "यूज़र सपोर्ट: यदि कोई एड अटक जाता है, तो पेज रीलोड करें या तेज़ इंटरनेट का उपयोग करें।",
    task_earn: "छोटे कार्यों को पूरा करें और अपनी कमाई बढ़ाएं!",
    task_tab: "कार्य",
    leaders_tab: "लीडरबोर्ड",
    home_tab: "मुख्यपृष्ठ",
    ads_tab: "विज्ञापन",
    menu_tab: "मेन्यू",
    sign_out: "सत्र लॉग आउट करें",
    confirm_logout: "क्या आप निश्चित रूप से अपने सेशन से लॉग आउट करना चाहते हैं?",
    total_members: "कुल सक्रिय सदस्य",
    verified_badge: "सत्यापित सदस्य",
    login_title: "सुरक्षित प्रवेश द्वार",
    signup_title: "नया खाता पंजीकृत करें",
    login_prompt: "अपने क्रेडेंशियल्स के साथ संकेतित करें",
    signup_prompt: "सुरक्षित माइक्रोटॉस्किंग और आजीवन निकासी हेतु अभी जुड़ें!",
    fullname_label: "आपका पूरा नाम",
    username_label: "यूज़रनेम",
    password_label: "पासवर्ड दर्ज करें",
    confirm_password_label: "पासवर्ड की पुष्टि करें",
    refercode_label: "रेफरल कोड (वैकल्पिक)",
    agreement_consent: "मैं CashHive की शर्तों और प्रति डिवाइस एक खाते के नियम से सहमत हूं।",
    already_member: "मौजूदा खाते में लॉग इन करें",
    new_member: "एक नया खाता बनाएँ",
    language_detect_msg: "🎁 रेफरल स्पॉन्सर कोड का स्वतः पता चला",

    quick_withdraw_sub: "अपनी कमाई तुरंत अपने खाते में प्राप्त करें",
    quick_invite: "मित्रों को आमंत्रित करें",
    quick_invite_sub: "सक्रिय सदस्य शामिल",
    daily_bonus: "दैनिक बोनस",
    daily_bonus_sub: "7 दिनों के दैनिक लॉगिन पुरस्कार",
    lucky_spin: "लकी स्पिन व्हील",
    lucky_spin_sub: "चक्र घुमाएँ और ৳3-5 जीतें",
    complete_tasks: "कार्य पूरे करें",
    watch_video_ads: "विज्ञापन वीडियो देखें",
    refer_link_copy_btn: "रेफर लिंक कॉपी करें",
    day: "दिन",
    active: "सक्रिय",
    claimed: "प्राप्त किया",
    claim: "प्राप्त करें",
    locked: "बंद",

    daily_bonus_title: "दैनिक बोनस सूची 🎁",
    daily_bonus_desc: "रोज़ाना क्लेम करें और अपने बटुए में शानदार लाभ प्राप्त करें!",
    daily_bonus_already_claimed: "आप आज का दैनिक क्लेम पूरा कर चुके हैं! कृपया कल पुनः प्रयास करें।",
    daily_bonus_claim_btn: "दैनिक चेक-इन (৳ {amount}) प्राप्त करें",
    daily_bonus_claimed_btn: "आज का बोनस लिया गया!",
    daily_bonus_alert_success: "🎉 बधाई हो! दैनिक चेक-इन बोनस आपके वॉलेट में जोड़ दिया गया है!",

    lucky_wheel_title: "लकी व्हील स्पिन 🎡",
    lucky_wheel_desc: "पहिया घुमाकर अपनी किस्मत आज़माएँ! 5 रुपये तक का इनाम पाने का सुनहरा अवसर।",
    wheel_center_text_1: "लकी",
    wheel_center_text_2: "स्पिन",
    wheel_cycle_hint: "💡 आज अपनी किस्मत आजमाने के लिए पहिया घुमाएं! प्रतिदिन 1 बार मुफ्त स्पिन कर सकते हैं।",
    wheel_spin_btn: "पहिया घुमाएं (Start Spin)",
    wheel_spin_disabled: "आज का स्पिन पूरा हो गया है!",
    wheel_spinning: "पहिया घूम रहा है... कृपया प्रतीक्षा करें",
    wheel_alert_success: "🎉 बधाई हो! आपने पहिया घुमाकर इनाम जीता है जो सीधे वॉलेट में जोड़ दिया गया है!",
    wheel_alert_empty: "आज निराशा हाथ लगी! कल पुनः किस्मत आज़माएँ निश्चित उपहार के लिए!",
    wheel_slice_empty: "खाली 😢",
    wheel_slice_taka: "৳ {amount} 💰",

    hd_sponsor_casting: "HD SPONSOR CASTING",
    buffering: "लोड हो रहा है...",
    remaining_seconds: "शेष {seconds} सेकंड",
    ready: "तैयार ✓",
    server_connecting: "सर्वर से जुड़ रहा है...",
    media_loading: "मीडिया स्ट्रीम लोड हो रही है",
    generator_loading: "हाई स्पीड वीडियो लिंक तैयार हो रहा है...",
    view_ad_carefully: "अपना इनाम पाने के लिए पूरा विज्ञापन ध्यान से देखें!",
    ad_reward_credited: "सीधे बटुए में जमा किया गया!",
    collect_reward_btn: "इनाम प्राप्त करें",
    user_panel_support_msg: "💡 सहायता: यदि विज्ञापन रुक जाता है, तो कृपया पृष्ठ को फिर से लोड करें।",
    ad_limit_reached_alert: "❌ आज की सीमा समाप्त हो गई है! कृपया कल वापस आएं।",

    leaderboard_header_title: "लीडरबोर्ड (शीर्ष कमाई करने वाले)",
    leaderboard_header_desc: "लाइव शीर्ष कमाई करने वाले सदस्यों की सूची। आगे रहने के लिए दैनिक कार्य करें!",
    your_rank: "आपका रैंक",
    total_income: "कुल आय",
    rank_and_user: "रैंक और उपयोगकर्ता",
    balance: "बैलेंस",
    you: "आप",
    taka_currency: "৳ Taka",
    leaderboard_footer_tip: "सप्ताह के शीर्ष 3 प्रदर्शनकर्ताओं को सीधे जैकपॉट बोनस दिया जाएगा! अधिक कार्य करें।",

    withdraw_banner_title: "🔥 निकासी की सीमाएं 🔥",
    withdraw_banner_desc: "न्यूनतम निकासी ৳100 और अधिकतम निकासी ৳25,000!",
    payment_audited_badge: "SECURE AUDITED PAYMENT",
    withdraw_method_title: "भुगतान का प्रकार चुनें",
    withdraw_method_desc: "हमारे विश्वसनीय नेटवर्क के माध्यम से अपने पैसे सीधे निकालें।",
    mobile_wallet_number_label: "मोबाइल वॉलेट नंबर (11 अंक):",
    placeholder_wallet_number: "अपना नंबर दर्ज करें (01XXXXXXXXX)",
    withdraw_amount_label: "निकासी राशि (৳100 - 25,000):",
    placeholder_withdraw_amount: "राशि दर्ज करें",
    withdraw_submit_btn: "निकासी का अनुरोध सबमिट करें 💸",
    withdraw_submitting: "प्रोसेस हो रहा है...",
    withdraw_success_msg: "आपका निकासी अनुरोध सबमिट कर दिया गया है! प्रशासन 12 घंटों में भुगतान करेगा।",
    withdraw_empty_err: "कृपया वैध राशि दर्ज करें।",
    withdraw_phone_err: "कृपया वैध 11 अंकों का वॉलेट मोबाइल नंबर दें।",
    withdraw_balance_err: "अपर्याप्त बटुआ बैलेंस!",
    withdraw_min_err: "न्यूनतम निकासी सीमा ৳100.00 है।",
    withdraw_max_err: "अधिकतम निकासी सीमा ৳25,000.00 है।"
  },
  UR: {
    welcome_notice: "ہماری ویب سائٹ پر خوش آمدید۔ ایمانداری سے کام کریں اور لامحدود کمائیں۔ ہم آپ کو 24 گھنٹوں کے اندر ادائیگی یقینی بنائیں گے۔",
    notice_title: "سرکاری اعلان",
    notice_guarantee_title: "🛡️ ہماری سرکاری ضمانت",
    notice_guarantee_desc: "ایمانداری سے کام کریں، لامحدود کام کریں اور واپسی کی درخواست کریں۔ ادائیگی 24 گھنٹوں میں ہو گی!",
    notice_read_close: "قبول کریں / بند کریں",
    notice_close: "بند کریں",
    available_balance: "موجودہ بیلنس",
    withdraw: "رقم نکالیں",
    withdraw_action: "کیش نکالیں",
    referrals: "ریفرل کوڈ",
    referrals_earn: "دوستوں کو ریفر کریں اور زبردست کمیشن کمائیں!",
    copy_referral_link: "اپنا ریفرل لنک کاپی کریں:",
    copied_msg: "لنک کاپی ہو گیا! ✓",
    ads_watched: "دیکھے گئے",
    ads_remaining: "باقی بچیں",
    ads_total: "کل لمٹ",
    reward_per_ad: "فی ایڈ انعام کی قیمت: ৳0.50",
    show_ad: "اشتہار دیکھیں (Show Ad)",
    ads_exhausted: "آج کے لیے اشتہارات ختم! کل دوبارہ تشریف لائیں۔",
    ad_desc: "ویڈیو مکمل لوڈ ہونے تک انتظار کریں۔ اپنے بٹوے میں رقم جمع کرنے کے لیے کلیم بٹن پر کلک کریں۔",
    premium_ads_hub: "پریمیم ایڈز ہب",
    earn_ad_title: "ویڈیو اشتہارات دیکھ کر یقینی انعامات کمائیں",
    daily_progress: "آج کی سرگرمی کی پیشرفت",
    collect_reward: "انعام حاصل کریں",
    sec_payout_hint: "صارف پینل سپورٹ: اگر کوئی ایڈ لوڈ نہ ہو تو صفحہ دوبارہ لوڈ کریں یا تیز انٹرنیٹ استعمال کریں۔",
    task_earn: "آسان مائیکرو ٹاسک مکمل کریں اور روزانہ کی آمدنی کو بڑھائیں!",
    task_tab: "ٹاسک",
    leaders_tab: "لیڈرز",
    home_tab: "ہوم پینل",
    ads_tab: "ایڈز",
    menu_tab: "مینو",
    sign_out: "سیشن لاگ آؤٹ کریں",
    confirm_logout: "کیا آپ واقعی اپنا سیشن بند کرنا چاہتے ہیں؟",
    total_members: "کل فعال ممبران",
    verified_badge: "تصدیق شدہ ممبر",
    login_title: "داخلہ پورٹل",
    signup_title: "نیا اکاؤنٹ بنائیں",
    login_prompt: "اپنے لاگ ان کواڈ کے ساتھ سیشن میں داخل ہوں",
    signup_prompt: "لائف ٹائم باؤنٹی اور فوری ادائیگیوں کے لیے شامل ہوں!",
    fullname_label: "آپ کا پورا نام",
    username_label: "صارف نام",
    password_label: "پاس ورڈ درج کریں",
    confirm_password_label: "پاس ورڈ کی تصدیق کریں",
    refercode_label: "ریفرل کوڈ (اختیاری)",
    agreement_consent: "میں CashHive کی تمام شرائط اور ایک آلہ پر ایک اکاؤنٹ کی پالیسی سے متفق ہوں۔",
    already_member: "موجودہ اکاؤنٹ لاگ ان کریں",
    new_member: "نیا ممبر اکاؤنٹ بنائیں",
    language_detect_msg: "🎁 ریفرل سپانسر سسٹم کا خودکار پتہ چلا",

    quick_withdraw_sub: "اپنی کمائی فوری اپنے بینک میں وصول کریں",
    quick_invite: "دوستوں کو مدعو کریں",
    quick_invite_sub: "سرگرم ارکان شامل ہو گئے",
    daily_bonus: "روزانہ بونس",
    daily_bonus_sub: "7 دنوں کے لاگ ان انعامات",
    lucky_spin: "لاکی اسپن پہیہ",
    lucky_spin_sub: "پہیہ گھمائیں اور ৳3-5 جیتیں",
    complete_tasks: "ٹاسک مکمل کریں",
    watch_video_ads: "اشتہاری ویڈیوز دیکھیں",
    refer_link_copy_btn: "ریفر لنک کاپی کریں",
    day: "دن",
    active: "فعال",
    claimed: "حاصل کیا",
    claim: "حاصل کریں",
    locked: "بند",

    daily_bonus_title: "روزانہ بونس کی فہرست 🎁",
    daily_bonus_desc: "باقاعدگی سے کلیم کریں اور شاندار بونس اپنے بٹوے میں پائیں!",
    daily_bonus_already_claimed: "آپ آج کا کلیم پورا کر چکے ہیں! برائے مہربانی کل دوبارہ کوشش کریں۔",
    daily_bonus_claim_btn: "روزانہ چیک ان (৳ {amount}) حاصل کریں",
    daily_bonus_claimed_btn: "آج کا لاگ ان بونس لیا گیا ہے!",
    daily_bonus_alert_success: "🎉 مبارک ہو! روزانہ لاگ ان بونس کامیابی کے ساتھ آپ کے بٹوے میں شامل کر دیا گیا ہے!",

    lucky_wheel_title: "لاکی پہیہ اسپن 🎡",
    lucky_wheel_desc: "پہیہ گھما کر اپنی قسمت آزمائیں! 5 روپے تک کیش جیتنے کا سنہری موقع۔",
    wheel_center_text_1: "لاکی",
    wheel_center_text_2: "اسپن",
    wheel_cycle_hint: "💡 आज अपनी किस्मत आजमाएं! रोजाना 1 बार पहिया मुफ्त घुमाएं।",
    wheel_spin_btn: "پہیہ گھمائیں (Start Spin)",
    wheel_spin_disabled: "آج کا اسپن مکمل ہو چکا ہے!",
    wheel_spinning: "پہیہ گھوم رہا ہے... برائے مہربانی انتظار کریں",
    wheel_alert_success: "🎉 مبارک ہو! آپ نے اسپن سے کامیابی سے انعام جیتا ہے جو بٹوے میں شامل کر دیا گیا ہے!",
    wheel_alert_empty: "آج قسمت نے ساتھ نہیں دیا! یقینی انعام کے لیے کل دوبارہ کوشش کریں!",
    wheel_slice_empty: "خالی 😢",
    wheel_slice_taka: "৳ {amount} 💰",

    hd_sponsor_casting: "HD SPONSOR CASTING",
    buffering: "لوڈ ہو رہا ہے...",
    remaining_seconds: "باقی {seconds} سیکنڈ",
    ready: "تیار ہے ✓",
    server_connecting: "سرور سے رابطہ ہو رہا ہے...",
    media_loading: "میڈیا اسٹریم لوڈ ہو رہی ہے",
    generator_loading: "تیز ترین ویڈیو لنک تیار ہو رہا ہے...",
    view_ad_carefully: "اپنا انعام حاصل کرنے کے لیے پورا اشتہار دھیان سے دیکھیں!",
    ad_reward_credited: "سیدھے بٹوے میں جمع کیا گیا!",
    collect_reward_btn: "انعام حاصل کریں",
    user_panel_support_msg: "💡 مدد: اگر اشتہار رک جاتا ہے تو برائے مہربانی پیج دوبارہ لوڈ کریں۔",
    ad_limit_reached_alert: "❌ آج کی حد ختم ہو گئی ہے! برائے مہربانی کل دوبارہ آئیں۔",

    leaderboard_header_title: "لیڈرز اعزازی فہرست (سب سے زیادہ کمانے والے)",
    leaderboard_header_desc: "سب سے زیادہ آمدنی والے اراکین کی لائیو لسٹ۔ آگے رہنے کے لیے روزانہ کام کریں!",
    your_rank: "آپ کا رینک",
    total_income: "کل آمدنی",
    rank_and_user: "رینک اور صارف",
    balance: "بیلنس",
    you: "آپ",
    taka_currency: "৳ Taka",
    leaderboard_footer_tip: "ہفتے کے ٹاپ 3 ارکان کو براہ راست جیک پاٹ بونس دیا جائے گا! مزید کام کریں۔",

    withdraw_banner_title: "🔥 رقم نکالنے کی حدود 🔥",
    withdraw_banner_desc: "کم از کم واپسی ৳100 اور زیادہ سے زیادہ واپسی ৳25,000!",
    payment_audited_badge: "SECURE AUDITED PAYMENT",
    withdraw_method_title: "رقم نکالنے کا طریقہ منتخب کریں",
    withdraw_method_desc: "ہمارے قابل اعتماد نیٹ ورکس کے ذریعے اپنے پیسے براہ راست وصول کریں۔",
    mobile_wallet_number_label: "موبائل والٹ نمبر (11 ہندسے):",
    placeholder_wallet_number: "اپنا نمبر درج کریں (01XXXXXXXXX)",
    withdraw_amount_label: "واپسی کی رقم (৳100 - 25,000):",
    placeholder_withdraw_amount: "رقم درج کریں",
    withdraw_submit_btn: "رقم نکالنے کی درخواست ارسال کریں 💸",
    withdraw_submitting: "پروسیس ہو رہا ہے...",
    withdraw_success_msg: "آپ کی واپسی کی درخواست جمع کر دی گئی ہے! انتظام 12 گھنٹوں میں ادائیگی کرے گا۔",
    withdraw_empty_err: "برائے مہربانی درست رقم درج کریں۔",
    withdraw_phone_err: "برائے مہربانی والٹ کا درست 11 ہندسوں کا نمبر فراہم کریں۔",
    withdraw_balance_err: "بٹوے میں رقم ناکافی ہے!",
    withdraw_min_err: "کم از کم واپسی کی حد ৳100.00 ہے۔",
    withdraw_max_err: "زیادہ سے زیادہ واپسی کی حد ৳25,000.00 ہے۔"
  },
  AR: {
    welcome_notice: "مرحباً بكم في موقعنا الرسمي. يرجى العمل بكل أمانة وجدية، بمهام غير محدودة وسحوبات مضمونة وتتم معالجتها في غضون ٢٤ ساعة فقط!",
    notice_title: "الإشعار الرسمي",
    notice_guarantee_title: "🛡️ ضماننا الرسمي المعتمد",
    notice_guarantee_desc: "اعملوا بأمانة ونفذوا مهام غير محدودة واطلبوا رصيدكم. السحب مضمون في أقل من 24 ساعة إن شاء الله!",
    notice_read_close: "أوافق / إغلاق الإشعار",
    notice_close: "إغلاق",
    available_balance: "الرصيد المتاح",
    withdraw: "سحب الأموال",
    withdraw_action: "سحب الكاش",
    referrals: "الإحالات",
    referrals_earn: "ادعُ الأصدقاء واربح العمولات والمكافآت السخية!",
    copy_referral_link: "نسخ رابط الإحالة الخاص بك:",
    copied_msg: "تم النسخ بنجاح! ✓",
    ads_watched: "المشاهدات",
    ads_remaining: "المتبقي",
    ads_total: "الحد الأقصى",
    reward_per_ad: "مكافأة الإعلان الواحد: ৳٠.٥٠",
    show_ad: "شاهد الإعلان (Show Ad)",
    ads_exhausted: "لقد انتهى الحد اليومي الخاص بك! يرجى المحاولة غداً.",
    ad_desc: "انتظر حتى يتم تحميل الإعلان بالكامل وانتهاء المؤقت. اضغط على زر المطالبة لإضافة المكافآت لمحفظتك.",
    premium_ads_hub: "منصة الإعلانات المميزة",
    earn_ad_title: "شاهد الفيديوهات الدعائية واربح مكافآت مضمونة",
    daily_progress: "مستوى تقدم العمل اليومي",
    collect_reward: "جمع المكافأة المالية",
    sec_payout_hint: "لوحة المستخدم: في حال تعليق الإعلان، يرجى إعادة تحديث الصفحة أو الاتصال بمزود إنترنت أسرع.",
    task_earn: "قم بتنفيذ المهام البسيطة والمصغّرة لزيادة أرباحك اليومية!",
    task_tab: "المهام",
    leaders_tab: "المتصدرون",
    home_tab: "الرئيسية",
    ads_tab: "الإعلانات",
    menu_tab: "القائمة",
    sign_out: "تسجيل الخروج",
    confirm_logout: "هل أنت متأكد من رغبتك في تسجيل الخروج من جهازك؟",
    total_members: "إجمالي الأعضاء النشطين",
    verified_badge: "عضو موثق",
    login_title: "تسجيل الدخول الآمن",
    signup_title: "إنشاء حساب جديد",
    login_prompt: "سجل الدخول باستخدام بيانات حسابك السابقة",
    signup_prompt: "انضم الآن للعمل المصغر والحصول على عوائد مدى الحياة!",
    fullname_label: "الاسم الكامل",
    username_label: "اسم المستخدم",
    password_label: "كلمة المرور",
    confirm_password_label: "تأكيد كلمة المرور",
    refercode_label: "رمز الإحالة (اختياري)",
    agreement_consent: "أوافق على الشروط والسياسات الخاصة بـ CashHive واتعهد بامتلاك حساب واحد فقط.",
    already_member: "الدخول ببيانات حسابك الحالي",
    new_member: "تسجيل حساب مستخدم جديد",
    language_detect_msg: "🎁 تم التعرف التلقائي على رمز الإحالة والتوجيه",

    quick_withdraw_sub: "اسحب أرباحك مباشرة إلى حسابك بموثوقية",
    quick_invite: "دعوة الأصدقاء",
    quick_invite_sub: "عضواً نشطاً انضموا بنجاح",
    daily_bonus: "الحافز اليومي",
    daily_bonus_sub: "مكافأة تسجيل الدخول لـ 7 أيام متتالية",
    lucky_spin: "عجلة الحظ الدوارة",
    lucky_spin_sub: "أدر العجلة الملونة لتربح من ৳3 إلى ৳5",
    complete_tasks: "إكمال المهام",
    watch_video_ads: "مشاهدة الفيديوهات الإعلانية",
    refer_link_copy_btn: "نسخ رابط الإحالة",
    day: "يوم",
    active: "نشط",
    claimed: "تم تحصيلها",
    claim: "احصل الآن",
    locked: "مقفل",

    daily_bonus_title: "سجل مكافآت الدخول اليومي 🎁",
    daily_bonus_desc: "سجل دخولك لـ 7 أيام متتالية واحصل على هدايا مغرية مباشرة في محفظتك!",
    daily_bonus_already_claimed: "لقد قمت بتحصيل حافزك اليوم بالفعل! الرجوع غداً لتسجيل الدخول التالي.",
    daily_bonus_claim_btn: "تحصيل رصيد اليوم (৳ {amount})",
    daily_bonus_claimed_btn: "تم حصد حافز اليوم بنجاح!",
    daily_bonus_alert_success: "🎉 مبارك! تم إضافة حافز تسجيل الدخول اليومي بنجاح إلى رصيدك!",

    lucky_wheel_title: "عجلة الحظ الدوارة 🎡",
    lucky_wheel_desc: "اختبر حظك يومياً بإدارة العجلة الدوارة! فرصة ذهبية لربح كاش حتى 5 تاكا مجاناً.",
    wheel_center_text_1: "عجلة",
    wheel_center_text_2: "الحظ",
    wheel_cycle_hint: "💡 أدر العجلة اليوم واختبر حظك! يمكنك تدوير العجلة مجاناً مرة واحدة يومياً.",
    wheel_spin_btn: "إطلاق عجلة الحظ (Start Spin)",
    wheel_spin_disabled: "لقد استنفذت دورتك لهذا اليوم!",
    wheel_spinning: "العجلة تدور الآن... يرجى الانتظار",
    wheel_alert_success: "🎉 مبارك! لقد أدرت العجلة بنجاح وفزت برصيد مالي مضاف إلى حسابك!",
    wheel_alert_empty: "حظاً أوفر! دورة اليوم فارغة، ننتظرك غداً للفوز بالجوائز المضمونة!",
    wheel_slice_empty: "فارغ 😢",
    wheel_slice_taka: "৳ {amount} 💰",

    hd_sponsor_casting: "HD SPONSOR CASTING",
    buffering: "جاري التحميل...",
    remaining_seconds: "المتبقي {seconds} ثانية",
    ready: "جاهز ✓",
    server_connecting: "جاري الاتصال بالخوادم المشفرة للتغذية الإعلانية...",
    media_loading: "جاري تحميل التدفق الإعلاني وتوزيعه بالبث",
    generator_loading: "جاري توليد روابط البث السريع للجهات الراعية...",
    view_ad_carefully: "الرجاء كتم الصوت ومشاهدة كامل الإعلان لتحصل على أرباحك المباشرة!",
    ad_reward_credited: "تمت إضافتها بشكل فوري لمحفظتك بنجاح!",
    collect_reward_btn: "مطالبة وجني المكافأة الكاش",
    user_panel_support_msg: "💡 دعم المستخدم: في حال تعطل الإعلان أو بطء التحميل، يرجى إعادة إنعاش الصفحة والتشغيل.",
    ad_limit_reached_alert: "❌ انتهى حد المشاهدة اليومي! الرجوع غداً.",

    leaderboard_header_title: "المتصدرون (الأعضاء الأكثر جنياً للأرباح)",
    leaderboard_header_desc: "الأعضاء الأكثر ربحاً على البث المباشر. أنجز مهامك يومياً للبقاء في الطليعة!",
    your_rank: "ترتيبك الحالي",
    total_income: "إجمالي الأرباح",
    rank_and_user: "المرتبة والمستخدم",
    balance: "الرصيد",
    you: "أنت",
    taka_currency: "৳ Taka",
    leaderboard_footer_tip: "الأعضاء الثلاثة الأوائل كل أسبوع سيفوزون بجوائز كبرى كاش تضاف لمحفظتهم مباشرة!",

    withdraw_banner_title: "🔥 شروط وحدود سحب الأرباح 🔥",
    withdraw_banner_desc: "الحد الأدنى للسحب ৳١٠٠ والحد الأقصى هو ৳٢٥,٠٠٠ تاكا!",
    payment_audited_badge: "SECURE AUDITED PAYMENT",
    withdraw_method_title: "اختر بوابة وبنك سحب المستحقات",
    withdraw_method_desc: "اسحب رصيدك وكاشك مباشرة عبر أي من الشبكات المالية الموثوقة أدناه.",
    mobile_wallet_number_label: "رقم المحفظة الإلكترونية (11 خانة):",
    placeholder_wallet_number: "أدخل رقم هاتفك البنكي (01XXXXXXXXX)",
    withdraw_amount_label: "الرصيد المراد سحبه (৳١٠٠ - ٢٥,٠٠٠):",
    placeholder_withdraw_amount: "حدد كمية الكاش",
    withdraw_submit_btn: "إرسال طلب سحب المستحقات فوراً 💸",
    withdraw_submitting: "جاري معالجة معاملتك المالية...",
    withdraw_success_msg: "تم تسليم طلب السحب بنجاح! بوابتنا الآمنة ستدفع مستحقاتكم كاش في غضون 12 ساعة فقط.",
    withdraw_empty_err: "الرجاء تعبئة رصيد سحب صالح قانونياً.",
    withdraw_phone_err: "الرجاء توفير رقم هاتف وايز صالح ومكون من 11 رقماً صحيحاً.",
    withdraw_balance_err: "رصيدك غير كافٍ لتمرير هذه العملية!",
    withdraw_min_err: "عذراً! الحد الأدنى لمعاملة السحب هو ৳100.00 تاكا.",
    withdraw_max_err: "عذراً! عملية السحب الواحدة لا يمكن أن تتعدى ৳25,000.00 تاكا."
  }
};

/**
 * Highly innovative language auto-detection helper based on system locales and timezones
 */
export function autoDetectLanguage(): LanguageCode {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || "";
    const locale = (navigator.language || "").toLowerCase();
    
    if (tz.includes("Dhaka") || locale.startsWith("bn")) {
      return "BN";
    }
    if (tz.includes("Calcutta") || tz.includes("Delhi") || locale.startsWith("hi")) {
      return "HI";
    }
    if (tz.includes("Karachi") || locale.startsWith("ur")) {
      return "UR";
    }
    if (tz.includes("Riyadh") || tz.includes("Dubai") || tz.includes("Cairo") || locale.startsWith("ar")) {
      return "AR";
    }
  } catch (e) {
    // Fail-safe
  }
  return "BN"; // Default original
}

/**
 * Helper to dynamically translate text and automatically format placeholders
 */
export function translate(lang: LanguageCode, key: string, params?: Record<string, string | number>): string {
  let text = translations[lang]?.[key] || translations['BN']?.[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
    });
  }
  return text;
}
